server:
  port: 8090
spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/utils?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: postgres
      password: 123456

nutz:
  json:
    auto-unicode: false
    quote-name: true
    ignore-null: true
    null-as-emtry: true
    enabled: true
    mode: compact
  dao:
    runtime:
      create: true
      migration: false
      basepackage: com.example.alien.utils.entity
    sqlmanager:
      paths:
        - sqls